// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ6gJflk1X08OJF2L4iVJcrjvxnglEzk0',
    appId: '1:318800623579:web:a7bc493089b18174f8d9fe',
    messagingSenderId: '318800623579',
    projectId: 'rx-comrade',
    authDomain: 'rx-comrade.firebaseapp.com',
    storageBucket: 'rx-comrade.appspot.com',
    measurementId: 'G-R9MHFYYBL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMQ1GKc7XIMtOcZ0I6P_eDd-l3xUBXDcs',
    appId: '1:318800623579:android:8fa06b104ed0d14cf8d9fe',
    messagingSenderId: '318800623579',
    projectId: 'rx-comrade',
    storageBucket: 'rx-comrade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRkJ_11bVzWi7z2e3mBgIAbvXhd8iFsrI',
    appId: '1:318800623579:ios:0750bc51be789aabf8d9fe',
    messagingSenderId: '318800623579',
    projectId: 'rx-comrade',
    storageBucket: 'rx-comrade.appspot.com',
    iosClientId: '318800623579-9on8gc8bjdamafgekphk0je9ebcglv4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.rxComrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRkJ_11bVzWi7z2e3mBgIAbvXhd8iFsrI',
    appId: '1:318800623579:ios:0750bc51be789aabf8d9fe',
    messagingSenderId: '318800623579',
    projectId: 'rx-comrade',
    storageBucket: 'rx-comrade.appspot.com',
    iosClientId: '318800623579-9on8gc8bjdamafgekphk0je9ebcglv4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.rxComrade',
  );
}
